"""Tests for notlob.commands.cmd_build.

cmd_build assembles a module (with inlined deps where supported) and
writes the result to a single file in the requested output directory.
When no path is given it discovers the project from CWD and builds
every module.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

from notlob import __version__
from notlob.commands import cmd_build, _build_header


def _hlint_available() -> bool:
    if shutil.which("hlint"):
        return True
    if shutil.which("stack"):
        try:
            r = subprocess.run(
                ["stack", "exec", "--", "hlint", "--version"],
                capture_output=True, timeout=10,
            )
            return r.returncode == 0
        except Exception:
            pass
    return False

_HAS_HLINT = _hlint_available()
_HS_SKIP   = pytest.mark.skipif(not _HAS_HLINT, reason="hlint not found")


# ── Helpers ───────────────────────────────────────────────────

_PY_BINDING = (
    "#Test Project\n\n---\n\n"
    "#Binding\n"
    "    ~language python\n"
)

_HS_BINDING = (
    "#Test Project\n\n---\n\n"
    "#Binding\n"
    "    ~language haskell\n"
)


def _write(tmp_path: Path, name: str, content: str) -> Path:
    p = tmp_path / name
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    return p


def _py_project(tmp_path: Path) -> Path:
    _write(tmp_path, "binding.lob", _PY_BINDING)
    return tmp_path


def _hs_project(tmp_path: Path) -> Path:
    _write(tmp_path, "binding.lob", _HS_BINDING)
    return tmp_path


# ── _build_header ────────────────────────────────────────────

class TestBuildHeader:
    def test_python_uses_hash_comment(self):
        h = _build_header("#", "my/mod", "mod.lob")
        assert h.startswith("# Generated by notlob")

    def test_haskell_uses_double_dash(self):
        h = _build_header("--", "my/mod", "mod.lob")
        assert h.startswith("-- Generated by notlob")

    def test_contains_version(self):
        h = _build_header("#", "my/mod", "mod.lob")
        assert __version__ in h

    def test_contains_module_address(self):
        h = _build_header("#", "roman/numerals", "numerals.lob")
        assert "roman/numerals" in h

    def test_contains_source_filename(self):
        h = _build_header("#", "my/mod", "mod.lob")
        assert "mod.lob" in h

    def test_do_not_edit_warning(self):
        h = _build_header("#", "my/mod", "mod.lob")
        assert "Do not edit" in h


# ── Python build ──────────────────────────────────────────────

class TestCmdBuildPython:
    def test_creates_py_file(self, tmp_path):
        root = _py_project(tmp_path)
        lob = _write(root, "greeter.lob", (
            "#Greeter\n\n"
            "    def greet(name):\n"
            "        return f'hello {name}'\n"
        ))
        out = tmp_path / "dist"
        assert cmd_build(lob, out) == 0
        assert (out / "greeter.py").exists()

    def test_output_contains_code(self, tmp_path):
        root = _py_project(tmp_path)
        lob = _write(root, "greeter.lob", (
            "#Greeter\n\n"
            "    def greet(name):\n"
            "        return f'hello {name}'\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "greeter.py").read_text()
        assert "def greet" in source

    def test_creates_output_dir_if_absent(self, tmp_path):
        root = _py_project(tmp_path)
        lob = _write(root, "thing.lob", "#Thing\n\n    x = 1\n")
        out = tmp_path / "nested" / "dist"
        assert not out.exists()
        cmd_build(lob, out)
        assert out.exists()

    def test_slug_uses_address(self, tmp_path):
        """Module address slashes become underscores in filename."""
        root = _py_project(tmp_path)
        lob = _write(root, "pkg/utils.lob", "#Pkg Utils\n\n    x = 1\n")
        out = tmp_path / "dist"
        cmd_build(lob, out)
        assert (out / "pkg_utils.py").exists()

    def test_empty_module_returns_error(self, tmp_path):
        root = _py_project(tmp_path)
        lob = _write(root, "empty.lob", "#Empty\n\nJust prose, no code.\n")
        out = tmp_path / "dist"
        assert cmd_build(lob, out) == 1

    def test_claims_not_in_output(self, tmp_path):
        """~example and ~property blocks are not written to the build output."""
        root = _py_project(tmp_path)
        lob = _write(root, "nums.lob", (
            "#Nums\n\n"
            "    def double(x): return x * 2\n\n"
            "~example\n"
            "    double(3) == 6\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "nums.py").read_text()
        assert "double(3) == 6" not in source
        assert "def double" in source

    def test_returns_zero_on_success(self, tmp_path):
        root = _py_project(tmp_path)
        lob = _write(root, "thing.lob", "#Thing\n\n    x = 1\n")
        assert cmd_build(lob, tmp_path / "dist") == 0

    def test_parse_error_returns_one(self, tmp_path):
        bad = tmp_path / "bad.lob"
        bad.write_text("not valid lob ???\x00\x01", encoding="utf-8")
        assert cmd_build(bad, tmp_path / "dist") == 1

    def test_output_has_generated_header(self, tmp_path):
        root = _py_project(tmp_path)
        lob = _write(root, "greeter.lob", "#Greeter\n\n    x = 1\n")
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "greeter.py").read_text()
        assert "Generated by notlob" in source
        assert __version__ in source

    def test_header_uses_hash_comment_for_python(self, tmp_path):
        root = _py_project(tmp_path)
        lob = _write(root, "greeter.lob", "#Greeter\n\n    x = 1\n")
        out = tmp_path / "dist"
        cmd_build(lob, out)
        first_line = (out / "greeter.py").read_text().splitlines()[0]
        assert first_line.startswith("# ")

    def test_dep_inlined(self, tmp_path):
        """A Python module that references another lob module gets it
        inlined -- regression test for the build artifact previously
        omitting cross-module dependency code entirely (NameError at
        execution time, since notlob test/run resolve #References via
        ModuleCache at runtime, but a build artifact has no loader)."""
        root = _py_project(tmp_path)
        _write(root, "roman/numerals.lob", (
            "#Roman Numerals\n\n"
            "    def to_roman(n):\n"
            "        return 'I' * n\n"
        ))
        lob = _write(root, "roman/numerals/app.lob", (
            "#Roman Numerals App\n\n"
            "    RESULT = to_roman(3)\n\n"
            "---\n\n"
            "#References\n"
            "    #Roman Numerals\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "roman_numerals_app.py").read_text()
        assert "def to_roman" in source
        assert "RESULT" in source

    def test_dep_inlined_artifact_is_executable(self, tmp_path):
        """The build artifact must actually run standalone, not just
        contain the dependency's source as text -- assembling without
        error was never the failure mode; execution was."""
        root = _py_project(tmp_path)
        _write(root, "roman/numerals.lob", (
            "#Roman Numerals\n\n"
            "    def to_roman(n):\n"
            "        return 'I' * n\n"
        ))
        lob = _write(root, "roman/numerals/app.lob", (
            "#Roman Numerals App\n\n"
            "    RESULT = to_roman(3)\n\n"
            "---\n\n"
            "#References\n"
            "    #Roman Numerals\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "roman_numerals_app.py").read_text()
        ns: dict = {}
        exec(source, ns)  # must not raise NameError for to_roman
        assert ns["RESULT"] == "III"

    def test_bare_run_wrapped_in_main_guard(self, tmp_path):
        root = _py_project(tmp_path)
        lob = _write(root, "thing.lob", (
            "#Thing\n\n    x = 1\n\n~run\n    print(x)\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "thing.py").read_text()
        assert 'if __name__ == "__main__":' in source
        guard_pos = source.index('if __name__ == "__main__":')
        body_pos = source.index("print(x)")
        assert body_pos > guard_pos

    def test_on_invocation_same_as_bare(self, tmp_path):
        root = _py_project(tmp_path)
        lob = _write(root, "thing.lob", (
            "#Thing\n\n    x = 1\n\n~run on-invocation\n    print(x)\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "thing.py").read_text()
        assert 'if __name__ == "__main__":' in source

    def test_on_load_unconditional_no_guard(self, tmp_path):
        root = _py_project(tmp_path)
        lob = _write(root, "thing.lob", (
            "#Thing\n\n    x = 1\n\n~run on-load\n    print(x)\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "thing.py").read_text()
        assert 'if __name__ == "__main__":' not in source
        assert "print(x)" in source

    def test_on_load_and_on_invocation_coexist(self, tmp_path):
        root = _py_project(tmp_path)
        lob = _write(root, "thing.lob", (
            "#Thing\n\n    x = 1\n\n"
            "~run on-load\n    print('load')\n\n"
            "~run on-invocation\n    print('invocation')\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "thing.py").read_text()
        guard_pos = source.index('if __name__ == "__main__":')
        load_pos = source.index("print('load')")
        invocation_pos = source.index("print('invocation')")
        assert load_pos < guard_pos < invocation_pos

    def test_execution_regression_run_vs_import(self, tmp_path):
        """The generated guard must actually discriminate run-vs-import,
        not just look plausible as text."""
        root = _py_project(tmp_path)
        lob = _write(root, "thing.lob", (
            "#Thing\n\n    x = 1\n\n"
            "~run on-load\n    LOAD_FIRED.append(1)\n\n"
            "~run on-invocation\n    INVOCATION_FIRED.append(1)\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "thing.py").read_text()

        imported_ns = {"__name__": "not_main",
                        "LOAD_FIRED": [], "INVOCATION_FIRED": []}
        exec(source, imported_ns)
        assert imported_ns["LOAD_FIRED"] == [1]
        assert imported_ns["INVOCATION_FIRED"] == []

        run_ns = {"__name__": "__main__",
                   "LOAD_FIRED": [], "INVOCATION_FIRED": []}
        exec(source, run_ns)
        assert run_ns["LOAD_FIRED"] == [1]
        assert run_ns["INVOCATION_FIRED"] == [1]

    def test_dep_run_claim_not_inlined(self, tmp_path):
        """Only the target module's own ~run fires -- a dependency's
        ~run claim must not be pulled into the artifact."""
        root = _py_project(tmp_path)
        _write(root, "roman/numerals.lob", (
            "#Roman Numerals\n\n"
            "    def to_roman(n):\n"
            "        return 'I' * n\n\n"
            "~run\n"
            "    print('should not appear')\n"
        ))
        lob = _write(root, "roman/numerals/app.lob", (
            "#Roman Numerals App\n\n"
            "    RESULT = to_roman(3)\n\n"
            "~run\n"
            "    print('app ran')\n\n"
            "---\n\n"
            "#References\n"
            "    #Roman Numerals\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "roman_numerals_app.py").read_text()
        assert "print('app ran')" in source
        assert "print('should not appear')" not in source


# ── Haskell build ─────────────────────────────────────────────

@_HS_SKIP
class TestCmdBuildHaskell:
    def test_creates_hs_file(self, tmp_path):
        root = _hs_project(tmp_path)
        lob = _write(root, "roman/numerals.lob", (
            "#Roman Numerals\n\n"
            "    toRoman :: Int -> String\n"
            "    toRoman 0 = \"\"\n"
            "    toRoman n = \"I\"\n"
        ))
        out = tmp_path / "dist"
        assert cmd_build(lob, out) == 0
        assert (out / "roman_numerals.hs").exists()

    def test_output_has_module_header(self, tmp_path):
        root = _hs_project(tmp_path)
        lob = _write(root, "roman/numerals.lob", (
            "#Roman Numerals\n\n"
            "    toRoman :: Int -> String\n"
            "    toRoman 0 = \"\"\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "roman_numerals.hs").read_text()
        assert "module RomanNumerals where" in source

    def test_output_has_generated_header(self, tmp_path):
        root = _hs_project(tmp_path)
        lob = _write(root, "roman/numerals.lob", (
            "#Roman Numerals\n\n"
            "    toRoman :: Int -> String\n"
            "    toRoman 0 = \"\"\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "roman_numerals.hs").read_text()
        assert "Generated by notlob" in source
        assert __version__ in source

    def test_header_uses_double_dash_for_haskell(self, tmp_path):
        root = _hs_project(tmp_path)
        lob = _write(root, "roman/numerals.lob", (
            "#Roman Numerals\n\n"
            "    toRoman :: Int -> String\n"
            "    toRoman 0 = \"\"\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        first_line = (out / "roman_numerals.hs").read_text().splitlines()[0]
        assert first_line.startswith("-- ")

    def test_dep_inlined(self, tmp_path):
        """A Haskell module that imports another lob module gets it inlined."""
        root = _hs_project(tmp_path)
        _write(root, "roman/numerals.lob", (
            "#Roman Numerals\n\n"
            "    toRoman :: Int -> String\n"
            "    toRoman 0 = \"\"\n"
            "    toRoman n = \"I\"\n"
        ))
        lob = _write(root, "roman/numerals/app.lob", (
            "#Roman Numerals App\n\n"
            "    main :: IO ()\n"
            "    main = putStrLn (toRoman 1)\n\n"
            "---\n\n"
            "#References\n"
            "    #Roman Numerals\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "roman_numerals_app.hs").read_text()
        # Dep code should be present in the single output file.
        assert "toRoman" in source
        assert "main" in source

    def test_bare_run_body_included(self, tmp_path):
        root = _hs_project(tmp_path)
        lob = _write(root, "thing.lob", (
            "#Thing\n\n"
            "    greet :: String\n"
            "    greet = \"hi\"\n\n"
            "~run\n"
            "    main :: IO ()\n"
            "    main = putStrLn greet\n"
        ))
        out = tmp_path / "dist"
        assert cmd_build(lob, out) == 0
        source = (out / "thing.hs").read_text()
        assert "main = putStrLn greet" in source

    def test_on_invocation_same_as_bare(self, tmp_path):
        root = _hs_project(tmp_path)
        lob = _write(root, "thing.lob", (
            "#Thing\n\n"
            "    greet :: String\n"
            "    greet = \"hi\"\n\n"
            "~run on-invocation\n"
            "    main :: IO ()\n"
            "    main = putStrLn greet\n"
        ))
        out = tmp_path / "dist"
        assert cmd_build(lob, out) == 0
        source = (out / "thing.hs").read_text()
        assert "main = putStrLn greet" in source

    def test_on_load_errors_without_writing_artifact(self, tmp_path, capsys):
        root = _hs_project(tmp_path)
        lob = _write(root, "thing.lob", (
            "#Thing\n\n"
            "    greet :: String\n"
            "    greet = \"hi\"\n\n"
            "~run on-load\n"
            "    main :: IO ()\n"
            "    main = putStrLn greet\n"
        ))
        out = tmp_path / "dist"
        assert cmd_build(lob, out) == 1
        assert not (out / "thing.hs").exists()
        err = capsys.readouterr().err
        assert "ERROR" in err
        assert "on-load" in err
        assert "equivalent for this binding" in err


# ── Project-mode build (no path arg) ─────────────────────────

class TestCmdBuildProjectMode:
    def test_builds_all_modules(self, tmp_path, monkeypatch):
        """No path arg builds every module in the project."""
        root = _py_project(tmp_path)
        _write(root, "alpha.lob", "#Alpha\n\n    x = 1\n")
        _write(root, "beta.lob",  "#Beta\n\n    y = 2\n")
        out = tmp_path / "dist"
        monkeypatch.chdir(root)
        assert cmd_build(output_dir=out) == 0
        assert (out / "alpha.py").exists()
        assert (out / "beta.py").exists()

    def test_skips_binding_lob(self, tmp_path, monkeypatch):
        """binding.lob is not included in the build output."""
        root = _py_project(tmp_path)
        _write(root, "mod.lob", "#Mod\n\n    x = 1\n")
        out = tmp_path / "dist"
        monkeypatch.chdir(root)
        cmd_build(output_dir=out)
        names = [p.name for p in out.iterdir()]
        assert not any("binding" in n for n in names)

    def test_no_project_root_returns_1(self, tmp_path, monkeypatch):
        """Without a binding.lob in CWD tree, returns exit code 1."""
        monkeypatch.chdir(tmp_path)
        assert cmd_build(output_dir=tmp_path / "dist") == 1

    def test_returns_zero_on_success(self, tmp_path, monkeypatch):
        root = _py_project(tmp_path)
        _write(root, "thing.lob", "#Thing\n\n    x = 1\n")
        monkeypatch.chdir(root)
        assert cmd_build(output_dir=tmp_path / "dist") == 0
