"""Tests for notlob.commands.cmd_build.

cmd_build assembles a module (with inlined deps where supported) and
writes the result to a single file in the requested output directory.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from notlob import __version__
from notlob.commands import cmd_build, _build_header


# ── Helpers ───────────────────────────────────────────────────

_PY_BINDING = (
    "#Test Project\n\n---\n\n"
    "#Binding\n"
    "    ~language python\n"
)

_HS_BINDING = (
    "#Test Project\n\n---\n\n"
    "#Binding\n"
    "    ~language haskell\n"
)


def _write(tmp_path: Path, name: str, content: str) -> Path:
    p = tmp_path / name
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    return p


def _py_project(tmp_path: Path) -> Path:
    _write(tmp_path, "binding.lob", _PY_BINDING)
    return tmp_path


def _hs_project(tmp_path: Path) -> Path:
    _write(tmp_path, "binding.lob", _HS_BINDING)
    return tmp_path


# ── _build_header ────────────────────────────────────────────

class TestBuildHeader:
    def test_python_uses_hash_comment(self):
        h = _build_header("#", "my/mod", "mod.lob")
        assert h.startswith("# Generated by notlob")

    def test_haskell_uses_double_dash(self):
        h = _build_header("--", "my/mod", "mod.lob")
        assert h.startswith("-- Generated by notlob")

    def test_contains_version(self):
        h = _build_header("#", "my/mod", "mod.lob")
        assert __version__ in h

    def test_contains_module_address(self):
        h = _build_header("#", "roman/numerals", "numerals.lob")
        assert "roman/numerals" in h

    def test_contains_source_filename(self):
        h = _build_header("#", "my/mod", "mod.lob")
        assert "mod.lob" in h

    def test_do_not_edit_warning(self):
        h = _build_header("#", "my/mod", "mod.lob")
        assert "Do not edit" in h


# ── Python build ──────────────────────────────────────────────

class TestCmdBuildPython:
    def test_creates_py_file(self, tmp_path):
        root = _py_project(tmp_path)
        lob = _write(root, "greeter.lob", (
            "#Greeter\n\n"
            "    def greet(name):\n"
            "        return f'hello {name}'\n"
        ))
        out = tmp_path / "dist"
        assert cmd_build(lob, out) == 0
        assert (out / "greeter.py").exists()

    def test_output_contains_code(self, tmp_path):
        root = _py_project(tmp_path)
        lob = _write(root, "greeter.lob", (
            "#Greeter\n\n"
            "    def greet(name):\n"
            "        return f'hello {name}'\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "greeter.py").read_text()
        assert "def greet" in source

    def test_creates_output_dir_if_absent(self, tmp_path):
        root = _py_project(tmp_path)
        lob = _write(root, "thing.lob", "#Thing\n\n    x = 1\n")
        out = tmp_path / "nested" / "dist"
        assert not out.exists()
        cmd_build(lob, out)
        assert out.exists()

    def test_slug_uses_address(self, tmp_path):
        """Module address slashes become underscores in filename."""
        root = _py_project(tmp_path)
        lob = _write(root, "pkg/utils.lob", "#Pkg Utils\n\n    x = 1\n")
        out = tmp_path / "dist"
        cmd_build(lob, out)
        assert (out / "pkg_utils.py").exists()

    def test_empty_module_returns_error(self, tmp_path):
        root = _py_project(tmp_path)
        lob = _write(root, "empty.lob", "#Empty\n\nJust prose, no code.\n")
        out = tmp_path / "dist"
        assert cmd_build(lob, out) == 1

    def test_claims_not_in_output(self, tmp_path):
        """~example and ~property blocks are not written to the build output."""
        root = _py_project(tmp_path)
        lob = _write(root, "nums.lob", (
            "#Nums\n\n"
            "    def double(x): return x * 2\n\n"
            "~example\n"
            "    double(3) == 6\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "nums.py").read_text()
        assert "double(3) == 6" not in source
        assert "def double" in source

    def test_returns_zero_on_success(self, tmp_path):
        root = _py_project(tmp_path)
        lob = _write(root, "thing.lob", "#Thing\n\n    x = 1\n")
        assert cmd_build(lob, tmp_path / "dist") == 0

    def test_parse_error_returns_one(self, tmp_path):
        bad = tmp_path / "bad.lob"
        bad.write_text("not valid lob ???\x00\x01", encoding="utf-8")
        assert cmd_build(bad, tmp_path / "dist") == 1

    def test_output_has_generated_header(self, tmp_path):
        root = _py_project(tmp_path)
        lob = _write(root, "greeter.lob", "#Greeter\n\n    x = 1\n")
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "greeter.py").read_text()
        assert "Generated by notlob" in source
        assert __version__ in source

    def test_header_uses_hash_comment_for_python(self, tmp_path):
        root = _py_project(tmp_path)
        lob = _write(root, "greeter.lob", "#Greeter\n\n    x = 1\n")
        out = tmp_path / "dist"
        cmd_build(lob, out)
        first_line = (out / "greeter.py").read_text().splitlines()[0]
        assert first_line.startswith("# ")


# ── Haskell build ─────────────────────────────────────────────

class TestCmdBuildHaskell:
    def test_creates_hs_file(self, tmp_path):
        root = _hs_project(tmp_path)
        lob = _write(root, "roman/numerals.lob", (
            "#Roman Numerals\n\n"
            "    toRoman :: Int -> String\n"
            "    toRoman 0 = \"\"\n"
            "    toRoman n = \"I\"\n"
        ))
        out = tmp_path / "dist"
        assert cmd_build(lob, out) == 0
        assert (out / "roman_numerals.hs").exists()

    def test_output_has_module_header(self, tmp_path):
        root = _hs_project(tmp_path)
        lob = _write(root, "roman/numerals.lob", (
            "#Roman Numerals\n\n"
            "    toRoman :: Int -> String\n"
            "    toRoman 0 = \"\"\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "roman_numerals.hs").read_text()
        assert "module RomanNumerals where" in source

    def test_output_has_generated_header(self, tmp_path):
        root = _hs_project(tmp_path)
        lob = _write(root, "roman/numerals.lob", (
            "#Roman Numerals\n\n"
            "    toRoman :: Int -> String\n"
            "    toRoman 0 = \"\"\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "roman_numerals.hs").read_text()
        assert "Generated by notlob" in source
        assert __version__ in source

    def test_header_uses_double_dash_for_haskell(self, tmp_path):
        root = _hs_project(tmp_path)
        lob = _write(root, "roman/numerals.lob", (
            "#Roman Numerals\n\n"
            "    toRoman :: Int -> String\n"
            "    toRoman 0 = \"\"\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        first_line = (out / "roman_numerals.hs").read_text().splitlines()[0]
        assert first_line.startswith("-- ")

    def test_dep_inlined(self, tmp_path):
        """A Haskell module that imports another lob module gets it inlined."""
        root = _hs_project(tmp_path)
        _write(root, "roman/numerals.lob", (
            "#Roman Numerals\n\n"
            "    toRoman :: Int -> String\n"
            "    toRoman 0 = \"\"\n"
            "    toRoman n = \"I\"\n"
        ))
        lob = _write(root, "roman/numerals/app.lob", (
            "#Roman Numerals App\n\n"
            "    main :: IO ()\n"
            "    main = putStrLn (toRoman 1)\n\n"
            "---\n\n"
            "#References\n"
            "    #Roman Numerals\n"
        ))
        out = tmp_path / "dist"
        cmd_build(lob, out)
        source = (out / "roman_numerals_app.hs").read_text()
        # Dep code should be present in the single output file.
        assert "toRoman" in source
        assert "main" in source
